Repository microsoft/fluentui-react-native, pull requests merged in 2021-08, with the labels that each got.

#827 Menu Button on macOS (Initial check in)
  apps/fluent-tester/src/FluentTester/testPages.macos.ts
  apps/ios/src/Podfile.lock
  apps/macos/src/Podfile
  apps/macos/src/Podfile.lock
  change/@fluentui-react-native-menu-button-26bd716c-ff81-4551-9326-0c03015ce9b5.json
  change/@fluentui-react-native-tester-bf0c3e15-9836-4c8f-a23a-6ebc07074240.json
  package.nuspec
  packages/components/MenuButton/FluentUIReactNativeMenuButton.podspec
  packages/components/MenuButton/README.md
  packages/components/MenuButton/macos/MSFMenuButtonManager.m
  packages/components/MenuButton/macos/MenuButton-Bridging-Header.h
  packages/components/MenuButton/macos/MenuButton.swift
  packages/components/MenuButton/macos/MenuButtonManager.swift
  packages/components/MenuButton/package.json
  packages/components/MenuButton/src/MenuButton.macos.tsx
Labels: AutoMerge :repeat:

#682 Use SwiftUI Avatar implementation from FluentUI Apple
  .ado/azure-pipelines.yml
  apps/fluent-tester/src/FluentTester/TestComponents/Avatar/AvatarTest.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Avatar/testImageSources.tsx
  apps/ios/src/Podfile.lock
  apps/macos/src/Podfile
  apps/macos/src/Podfile.lock
  change/@fluentui-react-native-experimental-avatar-36da0dec-2b70-4992-9ae8-2b7c77c70417.json
  change/@fluentui-react-native-experimental-native-button-38f66037-5ece-4319-9bb8-c0b75de6b41b.json
  change/@fluentui-react-native-experimental-native-date-picker-adf8595e-f0cd-48bc-8185-006b2031485b.json
  change/@fluentui-react-native-tester-b608e525-a63c-421f-a783-b280ebb8625d.json
  packages/experimental/Avatar/FluentUIReactNativeAvatar.podspec
  packages/experimental/Avatar/ios/AvatarView-Bridging-Header.h
  packages/experimental/Avatar/ios/AvatarViewManager.swift
  packages/experimental/Avatar/ios/MSFAvatarStorage.h
  packages/experimental/Avatar/ios/MSFAvatarStorage.m
  packages/experimental/Avatar/ios/MSFAvatarViewManager.m
  packages/experimental/Avatar/src/Avatar.tsx
  packages/experimental/NativeButton/FluentUIReactNativeButton.podspec
  packages/experimental/NativeDatePicker/FluentUIReactNativeDatePicker.podspec
Labels: AutoMerge :repeat:

#803 Adding Additional Documentation
  docs/next.config.js
  docs/package.json
  docs/pages/Components/Button.mdx
  docs/pages/Components/Callout.mdx
  docs/pages/Components/Checkbox.mdx
  docs/pages/Components/ContextualMenu.mdx
  docs/pages/Components/Link.mdx
  docs/pages/Components/MenuButton.mdx
  docs/pages/Components/Persona.mdx
  docs/pages/Components/PersonaCoin.mdx
  docs/pages/Components/Pressable.mdx
  docs/pages/Components/RadioGroup.mdx
  docs/pages/Components/Separator.mdx
  docs/pages/Components/Text.mdx
  docs/pages/Utilities/FocusTrapZone.mdx
  docs/pages/Utilities/FocusZone.mdx
  docs/pages/Utilities/Stack.mdx
  docs/pages/index.mdx
  packages/framework/README.MD
  packages/theming/README.md
Labels: documentation

#856 Revert "Add shadow tokens"
  change/@fluentui-react-native-theme-tokens-82aceac8-7b1d-4c9b-83c5-b9878d733801.json
  change/@fluentui-react-native-theme-tokens-c3d8e5bf-2ff1-45e7-a82b-da3caac1b668.json
  package.json
  packages/theming/theme-tokens/src/dark/reactnative/tokens-global.json
  packages/theming/theme-tokens/src/light/reactnative/tokens-global.json
  packages/theming/theme-tokens/src/pipeline-input/token-input.json
  yarn.lock
Labels: AutoMerge :repeat:

#855 Revert "Bump lage from 0.31.0 to 0.32.0"
  yarn.lock
Labels: AutoMerge :repeat:

#862 Win32 Shimmer and commonJS Shimmer unifying/cleaning changes
  apps/fluent-tester/src/E2E/common/BasePage.ts
  apps/fluent-tester/src/FluentTester/FluentTester.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Shimmer/ShimmerTest.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Shimmer/ShimmerTestElementSets.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Svg/SvgTest.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Test.tsx
  apps/fluent-tester/src/FluentTester/testPages.win32.ts
  apps/fluent-tester/src/FluentTester/theme/applyBrand.ts
  change/@fluentui-react-native-e24cd2c5-b6d4-4406-b851-281924b1efca.json
  change/@fluentui-react-native-experimental-shimmer-35a90fd0-5c64-4752-ab2e-c6c4d98f53dc.json
  change/@fluentui-react-native-experimental-text-08e163b6-2a2c-4ea9-bbf3-e9d8a421da94.json
  change/@fluentui-react-native-tester-fd0e2ee2-2937-4db9-ad0e-46da53572c76.json
  packages/experimental/Shimmer/src/Shimmer.styling.ts
  packages/experimental/Shimmer/src/Shimmer.styling.win32.ts
  packages/experimental/Shimmer/src/Shimmer.tsx
  packages/experimental/Shimmer/src/Shimmer.types.ts
  packages/experimental/Shimmer/src/Shimmer.types.win32.ts
  packages/experimental/Shimmer/src/Shimmer.win32.tsx
  packages/experimental/Shimmer/src/SvgShapeToPath.ts
  packages/experimental/Shimmer/src/consts.win32.ts
  packages/experimental/Shimmer/src/rectsRoundRectsCircles.svg
Labels: enhancement

#710 Update Native Apple Code for better downstream integration
  .ado/azure-pipelines.yml
  .ado/xcconfig/publish_overrides.xcconfig
  .ado/xcconfig/publish_overrides_ios_device.xcconfig
  .gitignore
  CONTRIBUTING.md
  apps/ios/src/Podfile.lock
  apps/macos/src/Podfile.lock
  change/@fluentui-react-native-experimental-avatar-476d367a-88db-4408-8936-6f8cb8db128f.json
  change/@fluentui-react-native-experimental-native-button-e32dd8b7-a8b9-4310-b73f-12b97efc3c30.json
  change/@fluentui-react-native-experimental-native-date-picker-63d95dab-5bab-4296-9700-9264d8db64b9.json
  change/@fluentui-react-native-focus-zone-9ea16c34-663b-4e89-96af-d78b229a9983.json
  change/@fluentui-react-native-menu-button-47a022d9-4ae3-4e40-9485-63f5a220f327.json
  change/@fluentui-react-native-native-radio-button-de33f38c-2107-41cd-ae87-39fc7b0748f4.json
  change/@fluentui-react-native-tester-31c5bc46-e4fc-4b05-acf6-0ab220e53f58.json
  change/@fluentui-react-native-tester-win32-796835b1-db59-4a38-8b21-f952789517b0.json
  package.nuspec
  packages/components/FocusZone/FluentUIReactNativeFocusZone.podspec
  packages/components/MenuButton/FluentUIReactNativeMenuButton.podspec
  packages/components/MenuButton/macos/MSFMenuButtonManager.h
  packages/components/NativeRadioButton/FluentUIReactNativeRadioButton.podspec
  packages/components/NativeRadioButton/macos/RadioButtonViewManager.h
  packages/experimental/Avatar/FluentUIReactNativeAvatar.podspec
  packages/experimental/Avatar/ios/MSFAvatarViewManager.h
  packages/experimental/Avatar/macos/MSFAvatarViewManager.h
  packages/experimental/NativeButton/FluentUIReactNativeButton.podspec
  packages/experimental/NativeButton/ios/MSFButtonViewManager.h
  packages/experimental/NativeButton/macos/MSFButtonViewManager.h
  packages/experimental/NativeDatePicker/FluentUIReactNativeDatePicker.podspec
  packages/experimental/NativeDatePicker/ios/MSFDatePickerManager.h
Labels: AutoMerge :repeat:

#756 Add Expander native component (WinUI 2.6)
  apps/fluent-tester/package.json
  apps/fluent-tester/src/FluentTester/TestComponents/Expander/ExpanderTest.tsx
  apps/fluent-tester/src/FluentTester/TestComponents/Expander/consts.ts
  apps/fluent-tester/src/FluentTester/TestComponents/Expander/index.ts
  apps/fluent-tester/src/FluentTester/testPages.ts
  apps/fluent-tester/src/FluentTester/testPages.windows.ts
  change/@fluentui-react-native-experimental-expander-ded57293-a3eb-4c0e-a8ee-6486ec59beef.json
  change/@fluentui-react-native-tester-fa6c5c21-a7e4-43ac-a631-f831de6b8c6b.json
  packages/experimental/Expander/CHANGELOG.json
  packages/experimental/Expander/CHANGELOG.md
  packages/experimental/Expander/README.md
  packages/experimental/Expander/babel.config.js
  packages/experimental/Expander/just.config.js
  packages/experimental/Expander/package.json
  packages/experimental/Expander/src/Expander.tsx
  packages/experimental/Expander/src/Expander.types.ts
  packages/experimental/Expander/src/index.ts
  packages/experimental/Expander/tsconfig.json
  packages/experimental/Expander/windows/.gitignore
  packages/experimental/Expander/windows/NuGet.Config
  packages/experimental/Expander/windows/ReactNativeExpander.sln
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderView.cpp
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderView.h
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderView.idl
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderViewManager.cpp
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderViewManager.h
  packages/experimental/Expander/windows/ReactNativeExpander/PropertySheet.props
  packages/experimental/Expander/windows/ReactNativeExpander/ReactNativeExpander.def
  packages/experimental/Expander/windows/ReactNativeExpander/ReactNativeExpander.vcxproj
  packages/experimental/Expander/windows/ReactNativeExpander/ReactNativeExpander.vcxproj.filters
  packages/experimental/Expander/windows/ReactNativeExpander/ReactPackageProvider.cpp
  packages/experimental/Expander/windows/ReactNativeExpander/ReactPackageProvider.h
  packages/experimental/Expander/windows/ReactNativeExpander/ReactPackageProvider.idl
  packages/experimental/Expander/windows/ReactNativeExpander/packages.config
  packages/experimental/Expander/windows/ReactNativeExpander/pch.cpp
  packages/experimental/Expander/windows/ReactNativeExpander/pch.h
  yarn.lock
Labels: AutoMerge :repeat:

#898 Custom theming documentation
  docs/pages/Theming/Basics.md
  docs/pages/Theming/CustomTheme.md
  docs/pages/Theming/DefaultThemes.md
  docs/pages/Theming/ThemedStylesheet.md
Labels: AutoMerge :repeat:

#909 Remove "MSF" prefix from Expander, triggering a change to fix the pipeline again
  change/@fluentui-react-native-experimental-expander-f59ae935-6b2b-4e1b-a4a1-df66b0b9f3d3.json
  packages/experimental/Expander/src/Expander.tsx
  packages/experimental/Expander/windows/ReactNativeExpander/ExpanderViewManager.cpp
Labels: AutoMerge :repeat:

#924 Fix bug in macOS MenuButton where default content is "NSMenuItem"
  change/@fluentui-react-native-menu-button-8c1eb193-a444-4003-b2ee-f2a6a8e6de16.json
  packages/components/MenuButton/macos/MenuButton.swift
Labels: AutoMerge :repeat:
