Repository microsoft/fluentui-react-native, pull requests merged in 2022-10, with the labels that each got.

#2188 chore: bump `@rnx-kit/cli` to 0.14.8
  apps/fluent-tester/metro.config.js
  apps/fluent-tester/package.json
  apps/win32/package.json
  change/@fluentui-react-native-tester-3c094a55-c66c-4e1a-8d5b-4dbde3039b17.json
  change/@fluentui-react-native-tester-win32-48abd40c-4671-436f-89a2-5607c6c0f840.json
  yarn.lock
Labels: Type: Dependencies, AutoMerge :repeat:

#2203 [Win32] Shimmer render issues due to SVG-implementation-dependent interpretation of negative radius
  change/@fluentui-react-native-experimental-shimmer-2f38a803-e7d9-42d8-8304-b09e3eb9aff9.json
  packages/experimental/Shimmer/src/SvgShapeToPath.ts
Labels: Type: Bug, Platform: Win32, Area: Shimmer

#2201 Align Avatar color hash algorithm to web
  apps/fluent-tester/src/TestComponents/Avatar/CustomizedAvatar.tsx
  change/@fluentui-react-native-avatar-3d411a31-e2f2-4f29-8aca-dac588d3a76c.json
  change/@fluentui-react-native-tester-fc4bdf5c-307f-4def-85cc-1f654a49eb12.json
  packages/components/Avatar/src/__tests__/Avatar.test.jsx
  packages/components/Avatar/src/getJavaHashCode.ts
  packages/components/Avatar/src/index.ts
  packages/components/Avatar/src/useAvatar.ts
Labels: AutoMerge :repeat:

#2211 Update notification shadow to use the shadow16 token value
  change/@fluentui-react-native-notification-2753caae-d6e4-479d-b35e-9a0033768f69.json
  packages/components/Notification/src/NotificationTokens.ts
  packages/components/Notification/src/__tests__/__snapshots__/Notification.test.tsx.snap
Labels: AutoMerge :repeat:

#2250 [Shadow] Update spec to explain why the shadow component was created
  change/@fluentui-react-native-experimental-shadow-f7559783-dea3-4fc2-8827-febbac6f2c77.json
  packages/experimental/Shadow/SPEC.md
Labels: AutoMerge :repeat:

#2276 Add brandColor alias tokens for android
  change/@fluentui-react-native-android-theme-82bf1b87-bcf5-4c9e-afc8-ccf1994ff1cc.json
  change/@fluentui-react-native-experimental-tabs-60bb9853-e71c-47e7-8c28-9c63a63af4aa.json
  change/@fluentui-react-native-link-8d0a0344-0455-40a0-b1d8-6063102a6e77.json
  change/@fluentui-react-native-tabs-6b2f6654-187f-4fd4-8b8a-2087aa65af22.json
  change/@fluentui-react-native-theme-tokens-1e1f7d86-b4dd-45b6-8fe2-d603ed6d112f.json
  change/@fluentui-react-native-theme-types-71735972-0638-447b-b122-6f875820f52c.json
  change/@fluentui-react-native-theming-utils-4ebb0155-5ed3-45a6-a1af-d11b72c6fca2.json
  packages/components/Link/src/__tests__/__snapshots__/Link.test.tsx.snap
  packages/components/Tabs/src/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/experimental/Tabs/src/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/theming/android-theme/src/__tests__/__snapshots__/android-theme.test.ts.snap
  packages/theming/theme-tokens/package.json
  packages/theming/theme-types/src/Color.types.ts
  packages/theming/theming-utils/src/mapPipelineToTheme.android.ts
  yarn.lock
Labels: AutoMerge :repeat:

#2285 MenuV1: Update types to PressablePropsExtended
  change/@fluentui-react-native-dropdown-88067f75-18e7-4ccf-af3a-10c69aeddd62.json
  change/@fluentui-react-native-menu-8acb28de-ffc3-4ba2-b8f7-066ec449461f.json
  change/@fluentui-react-native-switch-5f239592-19ad-47ab-aaad-3c028be798f4.json
  packages/components/Menu/SPEC.md
  packages/components/Menu/src/MenuTrigger/MenuTrigger.types.ts
  packages/components/Menu/src/MenuTrigger/getRevisedProps.ts
  packages/experimental/Dropdown/src/Dropdown/Dropdown.tsx
  packages/experimental/Dropdown/src/Dropdown/Dropdown.types.ts
  packages/experimental/Dropdown/src/Dropdown/useDropdown.ts
  packages/experimental/Dropdown/src/Option/Option.types.ts
  packages/experimental/Switch/SPEC.md
Labels: AutoMerge :repeat:
