Repository microsoft/fluentui-react-native, pull requests merged in 2023-01, with the labels that each got.

#2439 Migrate LinkV1 component to new package
  apps/fluent-tester/package.json
  apps/fluent-tester/src/TestComponents/LinkExperimental/E2ELinkTest.tsx
  apps/fluent-tester/src/TestComponents/LinkExperimental/InlineLinksTest.tsx
  apps/fluent-tester/src/TestComponents/LinkExperimental/LinkTest.tsx
  change/@fluentui-react-native-0abec747-2b77-43bb-bf71-237c29b1937b.json
  change/@fluentui-react-native-experimental-link-9c826536-ec46-4c89-82f1-a89a8caab7d1.json
  change/@fluentui-react-native-link-01461a88-c8d2-465d-a526-ed91bde63b10.json
  change/@fluentui-react-native-tester-cd7818d1-f91d-4a43-a097-51d8a210d750.json
  packages/components/Link/package.json
  packages/components/Link/src/Link.styling.ts
  packages/components/Link/src/Link.tsx
  packages/components/Link/src/Link.types.ts
  packages/components/Link/src/LinkTokens.android.ts
  packages/components/Link/src/LinkTokens.ts
  packages/components/Link/src/__tests__/Link.test.tsx
  packages/components/Link/src/__tests__/__snapshots__/Link.test.tsx.snap
  packages/components/Link/src/index.ts
  packages/components/Link/src/legacy/Link.settings.ts
  packages/components/Link/src/legacy/Link.tsx
  packages/components/Link/src/legacy/Link.types.ts
  packages/components/Link/src/legacy/__tests__/Link.test.tsx
  packages/components/Link/src/legacy/__tests__/__snapshots__/Link.test.tsx.snap
  packages/components/Link/src/useLink.ts
  packages/components/Link/tsconfig.json
  packages/experimental/Link/jest.config.js
  packages/experimental/Link/package.json
  packages/experimental/Link/src/Link.tsx
  packages/experimental/Link/src/Link.types.ts
  packages/experimental/Link/src/__tests__/Link.test.tsx
  packages/experimental/Link/src/__tests__/__snapshots__/Link.test.tsx.snap
  packages/experimental/Link/src/index.ts
  packages/experimental/Link/tsconfig.json
  packages/libraries/core/src/index.ts
Labels: AutoMerge :repeat:

#2437 Add click tests for LinkV1
  apps/E2E/src/LinkExperimental/pages/ExperimentalLinkPageObject.ts
  apps/E2E/src/LinkExperimental/specs/ExperimentalLink.spec.win.ts
  apps/fluent-tester/src/TestComponents/LinkExperimental/E2ELinkTest.tsx
  change/@fluentui-react-native-e2e-testing-34d3a9cc-6e1d-484c-ab84-8601eea35959.json
  change/@fluentui-react-native-tester-b16cebf5-e62b-4c62-b2d3-a622b1375fe9.json
Labels: AutoMerge :repeat:

#2483 Change default theme from a const object to a function that returns the object
  change/@fluentui-react-native-default-theme-602cc57a-63a1-4a26-9644-9e635e7a0716.json
  change/@fluentui-react-native-framework-061f0724-c25c-474d-8ad1-73387d605b64.json
  change/@fluentui-react-native-theme-4eedba7d-11e6-49e4-a9d8-e190a26d2a71.json
  change/@fluentui-react-native-win32-theme-73953f3f-ad20-4e9b-b4ba-1dc054dcd6f9.json
  change/@uifabricshared-foundation-compose-7cf40fbe-c55c-4135-b024-42471e6ab672.json
  change/@uifabricshared-theming-react-native-857b81df-52b2-412a-9dee-5b68a5488823.json
  packages/deprecated/foundation-compose/src/useStyling.ts
  packages/deprecated/theming-react-native/src/BaselinePlatformDefaults.ts
  packages/framework/framework/src/useFluentTheme.ts
  packages/framework/theme/README.md
  packages/theming/default-theme/src/__tests__/default-theme.test.ts
  packages/theming/default-theme/src/createDefaultTheme.ts
  packages/theming/default-theme/src/defaultTheme.ts
  packages/theming/win32-theme/src/getThemeTypography.ts
Labels: AutoMerge :repeat:

#2489 Show focus on Submenu item for keyboard access
  change/@fluentui-react-native-menu-6e8f4812-f534-4202-926f-e3a9b54d4fb0.json
  packages/components/Menu/src/MenuItem/useMenuItem.ts
  packages/components/Menu/src/MenuList/MenuList.tsx
Labels: AutoMerge :repeat:

#2494 [Switch] Disable state a11y fix
  change/@fluentui-react-native-switch-e8fa82d1-7cc1-49f6-9610-b4bf1781f960.json
  packages/experimental/Switch/src/__tests__/__snapshots__/Switch.test.tsx.snap
  packages/experimental/Switch/src/useSwitch.ts
Labels: AutoMerge :repeat:

#2495 [Switch] Add examples and update spec
  change/@fluentui-react-native-switch-ad46935a-5fe4-42e7-9d93-205f556c0a9b.json
  packages/experimental/Switch/SPEC.md
  packages/experimental/Switch/assets/switch_sample_android.png
Labels: AutoMerge :repeat:

#2481 Set up iOS alias color tokens
  change/@fluentui-react-native-apple-theme-973260f3-3320-4d3c-b409-1650f9205921.json
  change/@fluentui-react-native-theme-tokens-07d59fd7-346d-4840-af85-4aea5c6ddc32.json
  change/@fluentui-react-native-theme-types-ca2fbd5f-b4cd-4f37-8d77-6a3912348246.json
  change/@fluentui-react-native-theming-utils-6d24d91b-4ecf-4d20-9965-c7e9e8d4e8f0.json
  packages/theming/apple-theme/package.json
  packages/theming/apple-theme/src/appleColors.ios.ts
  packages/theming/apple-theme/src/createiOSAliasTokens.ts
  packages/theming/apple-theme/src/getiOSTokens.ts
  packages/theming/theme-tokens/package.json
  packages/theming/theme-tokens/src/getShadowTokens.android.ts
  packages/theming/theme-tokens/src/getShadowTokens.ts
  packages/theming/theme-tokens/src/getTokens.android.ts
  packages/theming/theme-tokens/src/getTokens.ios.ts
  packages/theming/theme-tokens/src/getTokens.ts
  packages/theming/theme-tokens/src/index.ts
  packages/theming/theme-types/src/Color.types.ts
  packages/theming/theming-utils/src/mapPipelineToTheme.android.ts
  packages/theming/theming-utils/src/mapPipelineToTheme.ios.ts
  yarn.lock
Labels: AutoMerge :repeat:

#2503 RadioGroup Adding Re-Render Depth 2 Jest Test
  change/@fluentui-react-native-experimental-radio-group-660c83dd-89e2-4a8d-8abe-3f1c4960d6e8.json
  packages/experimental/RadioGroup/src/Radio/RadioExperimental.test.tsx
Labels: Platform: Win32, Area: RadioGroup

#2461 RadioGroup Narrator Selection State Bug Fix
  change/@fluentui-react-native-experimental-radio-group-3c3b0dc0-bf47-4e76-9d58-00ab8cb6cd59.json
  packages/experimental/RadioGroup/src/Radio/RadioExperimental.test.tsx
  packages/experimental/RadioGroup/src/Radio/__snapshots__/RadioExperimental.test.tsx.snap
  packages/experimental/RadioGroup/src/Radio/useRadio.win32.ts
  packages/experimental/RadioGroup/src/RadioGroup/RadioGroup.tsx
  packages/experimental/RadioGroup/src/RadioGroup/RadioGroup.types.ts
  packages/experimental/RadioGroup/src/RadioGroup/__snapshots__/RadioGroupExperimental.test.tsx.snap
  packages/experimental/RadioGroup/src/RadioGroup/radioGroupContext.ts
  packages/experimental/RadioGroup/src/RadioGroup/useRadioGroup.ts
Labels: Platform: Win32, Area: RadioGroup

#2515 Update main README
  README.md
Labels: Type: Documentation

#2511 [E2E Tests] Expand Android tests
  .ado/templates/android-dep-setup.yml
  apps/E2E/src/ActivityIndicator/pages/ActivityIndicatorPageObject.ts
  apps/E2E/src/Avatar/pages/AvatarPageObject.ts
  apps/E2E/src/Avatar/specs/Avatar.spec.win.ts
  apps/E2E/src/Badge/pages/BasicBadgePageObject.ts
  apps/E2E/src/ButtonLegacy/pages/ButtonLegacyPageObject.ts
  apps/E2E/src/ButtonLegacy/specs/Button.spec.android.ts
  apps/E2E/src/ButtonV1/pages/ButtonV1PageObject.ts
  apps/E2E/src/ButtonV1/specs/ButtonV1.spec.android.ts
  apps/E2E/src/ButtonV1/specs/ButtonV1.spec.win.ts
  apps/E2E/src/Callout/pages/CalloutPageObject.win.ts
  apps/E2E/src/Callout/specs/Callout.spec.win.ts
  apps/E2E/src/CheckboxLegacy/pages/CheckboxLegacyPageObject.ts
  apps/E2E/src/CheckboxV1/pages/CheckboxV1PageObject.ts
  apps/E2E/src/CheckboxV1/specs/CheckboxV1.spec.android.ts
  apps/E2E/src/CheckboxV1/specs/CheckboxV1.spec.win.ts
  apps/E2E/src/FocusTrapZone/pages/FocusTrapZonePageObject.win.ts
  apps/E2E/src/FocusZone/pages/FocusZonePageObject.ts
  apps/E2E/src/IconLegacy/pages/IconLegacyPageObject.ts
  apps/E2E/src/IconV1/pages/IconV1PageObject.ts
  apps/E2E/src/LinkLegacy/pages/LinkLegacyPageObject.ts
  apps/E2E/src/LinkLegacy/specs/LinkLegacy.spec.win.ts
  apps/E2E/src/LinkV1/pages/LinkV1PageObject.ts
  apps/E2E/src/LinkV1/specs/LinkV1.spec.win.ts
  apps/E2E/src/Menu/specs/Menu.spec.win.ts
  apps/E2E/src/Persona/pages/PersonaPageObject.ts
  apps/E2E/src/PersonaCoin/pages/PersonaCoinPageObject.ts
  apps/E2E/src/Pressable/pages/PressablePageObject.ts
  apps/E2E/src/RadioGroupV1/pages/RadioGroupV1PageObject.ts
  apps/E2E/src/RadioGroupV1/specs/RadioGroupV1.spec.android.ts
  apps/E2E/src/Separator/pages/SeparatorPageObject.ts
  apps/E2E/src/Shimmer/pages/ShimmerPageObject.win.ts
  apps/E2E/src/Svg/pages/SvgPageObject.ts
  apps/E2E/src/Switch/pages/SwitchPageObject.ts
  apps/E2E/src/TabsLegacy/pages/TabsLegacyPageObject.ts
  apps/E2E/src/TabsV1/pages/TabsV1PageObject.ts
  apps/E2E/src/TextV1/pages/TextV1PageObject.win.ts
  apps/E2E/src/Theme/pages/ThemePageObject.win.ts
  apps/E2E/src/Tokens/pages/TokensPageObject.win.ts
  apps/E2E/src/common/BasePage.ts
  apps/E2E/src/common/consts.ts
  apps/fluent-tester/src/FluentTester.tsx
  apps/fluent-tester/src/TestComponents/Button/ButtonTest.tsx
  change/@fluentui-react-native-e2e-testing-113fe3e9-5837-4db0-a19c-cc939c9bbc9e.json
  change/@fluentui-react-native-tester-178e2c4e-283f-4ef0-bf98-613fb6dc8e53.json
Labels: Platform: Android, Area : E2E Tests

#2519 Rename Tokens Test -> Color Tokens Test
  apps/E2E/src/ColorTokens/consts.ts
  apps/E2E/src/ColorTokens/pages/ColorTokensPageObject.win.ts
  apps/E2E/src/ColorTokens/specs/ColorTokens.spec.ios.ts
  apps/E2E/src/ColorTokens/specs/ColorTokens.spec.macos.ts
  apps/E2E/src/ColorTokens/specs/ColorTokens.spec.win.ts
  apps/E2E/src/Tokens/consts.ts
  apps/E2E/src/Tokens/pages/TokensPageObject.win.ts
  apps/E2E/src/Tokens/specs/Tokens.spec.ios.ts
  apps/E2E/src/Tokens/specs/Tokens.spec.macos.ts
  apps/E2E/src/Tokens/specs/Tokens.spec.win.ts
  apps/E2E/src/common/NavigateAppPage.ts
  apps/E2E/src/index.consts.ts
  apps/fluent-tester/src/TestComponents/ColorTokens/ColorTokenTest.tsx
  apps/fluent-tester/src/TestComponents/ColorTokens/index.ts
  apps/fluent-tester/src/TestComponents/Tokens/index.ts
  apps/fluent-tester/src/testPages.ts
  change/@fluentui-react-native-e2e-testing-3dd52f94-42a8-49fd-9060-6056dbecf1d8.json
  change/@fluentui-react-native-tester-155e52ae-55d3-46c0-850f-22768de53ec6.json
Labels: AutoMerge :repeat:

#2535 [Switch] Fix initial page load animation
  change/@fluentui-react-native-switch-e2c671fb-fdf2-44cd-aa57-270c2c56a58d.json
  packages/experimental/Switch/src/__tests__/__snapshots__/Switch.test.tsx.snap
  packages/experimental/Switch/src/useSwitch.ts
Labels: Platform: Android, Platform: iOS, Area : Switch

#2539 RadioGroup Spec & Migration Documentation
  apps/fluent-tester/src/TestComponents/RadioGroupV1/RadioGroupV1Test.tsx
  change/@fluentui-react-native-experimental-radio-group-e32e761a-469b-49fd-a671-aac3d9c2a9a7.json
  change/@fluentui-react-native-tester-1019f3e8-4962-4c68-b6dc-38228e32c325.json
  packages/experimental/RadioGroup/MIGRATION.md
  packages/experimental/RadioGroup/SPEC.md
  packages/experimental/RadioGroup/assets/controlled_radiogroup.png
  packages/experimental/RadioGroup/assets/disabled_item.png
  packages/experimental/RadioGroup/assets/disabled_radiogroup.png
  packages/experimental/RadioGroup/assets/horizontal_radiogroup.png
  packages/experimental/RadioGroup/assets/horizontal_stacked_radiogroup.png
  packages/experimental/RadioGroup/assets/required_radiogroup.png
  packages/experimental/RadioGroup/assets/subtext_radiogroup.png
  packages/experimental/RadioGroup/assets/uncontrolled_radiogroup.png
  packages/experimental/RadioGroup/src/Radio/Radio.types.ts
  packages/experimental/RadioGroup/src/RadioGroup/RadioGroup.types.ts
Labels: Platform: Win32, Area: RadioGroup

#2550 Integrate Shared color aliases
  change/@fluentui-react-native-android-theme-117df028-73a1-4df8-981a-5ad477f7f37d.json
  change/@fluentui-react-native-theme-tokens-2c5f7b34-b134-418d-b287-15823be73a22.json
  change/@fluentui-react-native-theme-types-2d694d7f-c1ed-4880-af50-d2d34f7b5fd9.json
  change/@fluentui-react-native-theming-utils-bd2566a7-1d0d-476e-af66-cb1ff0ddf423.json
  packages/theming/android-theme/src/__tests__/__snapshots__/android-theme.test.ts.snap
  packages/theming/theme-tokens/package.json
  packages/theming/theme-types/src/Color.types.ts
  packages/theming/theming-utils/src/mapPipelineToTheme.android.ts
  yarn.lock
Labels: AutoMerge :repeat:

#2538 Add global color tokens to color tokens tester page
  apps/fluent-tester/src/TestComponents/ColorTokens/ColorTokenTest.tsx
  change/@fluentui-react-native-e2e-testing-8254630e-ba51-4add-82cf-77fd568b6b4d.json
  change/@fluentui-react-native-tester-40aba41e-c31d-4d06-a07a-31014605fca1.json
Labels: AutoMerge :repeat:

#2544 Update notification shadow to use shadow16 in .ios.ts file
  change/@fluentui-react-native-notification-7979ad9f-f982-4743-b3d6-6ddb5c19f640.json
  packages/components/Notification/src/NotificationTokens.ios.ts
  packages/components/Notification/src/__tests__/__snapshots__/Notification.test.tsx.snap
Labels: AutoMerge :repeat:
